### PR TITLE
add docker secret support

### PR DESCRIPTION
**Pull request by hos-ftv**
This MR will add support for docker secrets. Using docker swarm or kubernetes this will provide a safer/cleaner way to pass the required credentials.

The secret file itself is has to be structured like a usual `.env` - file and will be "sourced" prior the default values will be applied.

### CODE REVIEW

**Comment by hos-ftv** [comment]
An other  approach could be to use the existing environment variables so that they could either hold the value itself or a path.

e.g.
```bash
MYSQL_ROOT_PASSWORD=12345
# or
MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_pw
```

And in `functions.sh`:
```bash
if [ -f $MYSQL_ROOT_PASSWORD ]; then
    MYSQL_ROOT_PASSWORD=`cat $MYSQL_ROOT_PASSWORD`
elif [ -z $MYSQL_ROOT_PASSWORD ]; then
   # apply defaults
fi
```

But there are 2 downside docker secrets got support this way. It is quite implicit and you have to maintain multiple secret - files instead of one.

**Comment by juanluisbaptiste** [comment]
Hi,

Thanks for the PR, I will test it out.

**Comment by juanluisbaptiste** [comment]
I currently don't have a swarm/k8 cluster, I tested that the PR does not break the default behavior and it does not, so I will merge it.

Thanks.

**Comment by hos-ftv** [comment]
Perfect, thanks!

**Pull request merged**
