### PR TITLE
fix issues with non-quoted variables

### PR DESCRIPTION
**Pull request by rdxmb**
this PR fixes the issues with non-quoted variables , described in https://github.com/juanluisbaptiste/docker-otrs/issues/126

### CODE REVIEW

**Comment by juanluisbaptiste** [comment]
Merged, thanks.

**Comment by rdxmb** [comment]
Have thanks for merging. What is the docker tag this will be pushed to?

**Comment by juanluisbaptiste** [comment]
For now, juanluisbaptiste/znuny:latest, with juanuisbaptiste/otrs because of the different tagged and broken versions, the latest docker tag points to 6.0.39 git tag, which is the last without issues, So I cannot build the latest tag from master. I will have to create a new branch off the 6.0.39 tag, cherry-pick this commit and build latest from that, but I do not have the time ATM.

**Comment by rdxmb** [comment]
I see, thanks for the information. Maybe I will build for myself ... . Kind regards.

**Pull request merged**
