### PR TITLE
Add parameter to disable mysqladmin ping

### PR DESCRIPTION
**Pull request by schadom**
This PR adds a new parameter `OTRS_CHECK_DATABASE=yes|no` which allows for mysqladmin ping to be disabled. Currently it's not possible to use the container with already existing OTRS databases.

### CODE REVIEW

**Comment by juanluisbaptiste** [comment]
Hi,

Can you explain your self better ? I have successfully connected to existing OTRS databases, both in outside servers or running containers with no issue. 

The point of mysqlping is just to monitor the database until it is available, so the OTRS container can connect to it and continue setting up/strting everything. If you are connecting to an already existing database then mysqlping will return true, the OTRS container setup will continue.

**Comment by schadom** [comment]
Hi @juanluisbaptiste, sure. In our case we cannot provide the container with our `MYSQL_ROOT_PASSWORD`, therefore we would like to skip `mysqlping`. This parameter is optional and set to `no` by default. The second problem as mentioned in #34 is related to the Sendmail:: params which are currently statically set in Config.pm. Due to OTRS's inheritance model, all settings set in Config.pm are persistent and have priority over all other settings set in OTRS sysconfig (database). As a result, currently it's not possible to use other Sendmail settings (other Sendmail::Method, SMTP Server, Port, etc.) within OTRS. Thanks

**Comment by juanluisbaptiste** [comment]
> Hi @juanluisbaptiste, sure. In our case we cannot provide the container with our MYSQL_ROOT_PASSWORD, therefore we would like allow for skipping mysqlping optionally. 

The problem doing this is that the container will not be able to know when the database is available and will try to setup the container regardless. Could you explain why you cannot provide MYSQL_ROOT_PASSWORD ? I'm not going to add a feature that I don't understand its purpose.

> The second problem as mentioned in #34 is related to the Sendmail:: params which are currently statically set in Config.pm. Due to OTRS's inheritance model, all settings set in Config.pm are persistent and have priority over the other settings from OTRS sysconfig (database). As a result, currently it's not possible to use other Sendmail settings (other Sendmail::Method, SMTP Server, Port, etc.) within OTRS. Thanks

Please keep the conversation about this on its own issue, and as I said over there, PR's are welcome.

**Comment by juanluisbaptiste** [comment]
Any comments ? or may I proceed to close this issue ?

**Comment by hos-ftv** [comment]
I provided a new pull request #62 which should address the issue @schadom stated. But except of handling the symptom I tried to fix the cause.

**Comment by juanluisbaptiste** [comment]
Please don't continue to mix both issues, this one is about disabling _mysqlping_, pull request #62 is about _SendmailModule_ configuration.

**Comment by schadom** [comment]
> Any comments ? or may I proceed to close this issue ?

Sure, let me explain it a bit more in detail. We are running a central database cluster for our databases including the otrs database but are running the otrs container on our docker nodes. We would like to use the existing, external otrs database but do not want to expose the database servers root user to the container.  Does this make sense?

**Comment by juanluisbaptiste** [comment]
Well, for this you could just set _MYSQL_ROOT_USER_ to whatever non-root user you want that also has create database privileges.

**Comment by hos-ftv** [comment]
> do not want to expose the database clusters root user to the container

This is where docker secrets come into place. I don't know if you've recognized it but support for docker secrets got implemented some weeks ago.

[Manage sensitive data with Docker secrets](https://docs.docker.com/engine/swarm/secrets/)

**Comment by juanluisbaptiste** [comment]
Yes I know what docker secrets are, but that has more to do with where your container secrets are stored rathern than how those secrets are sent to the db server. 

I think you can as I said use _MYSQL_ROOT_USER_ to setup a non-root user that can create the otrs database when the container starts, there's no need to disable the db container ping.

**Pull request closed without merging**
