### PR TITLE
make SendmailModule configurable

### LINKED ISSUE #34: Make SendmailModule configurable
Hello,

currently the `SendmailModule` settings are static in Kernel/Config.pm:
https://github.com/juanluisbaptiste/docker-otrs/blob/master/otrs/Config.pm#L96

It would be nice if those could be removed or overwritten with environment variables, for example we would like to use  `SendmailModule => 'Kernel::System::Email::SMTPTLS'` with custom settings from the DB.

The otrs config params are;

	SendmailModule
	SendmailModule::AuthUser
	SendmailModule::AuthPassword
	SendmailModule::Host
	SendmailModule::Port

Thanks

### PR DESCRIPTION
**Pull request by hos-ftv**
fixes #34 

I've added a switch to completely disable writing the smtp-settings to the Config.pm which allows us to configure those settings via SysConf.

P.S.
Oh, btw. Feel free to edit anything you like if there are any mistakes (i.e. spelling, prefered syntax).

### CODE REVIEW

**Comment by hos-ftv** [comment]
May this also addresses the issue which raised pull request #55

**Comment by hos-ftv** [comment]
Oh, btw. Feel free to edit anything you like if there are any mistakes (i.e. spelling, prefered syntax).

**Comment by juanluisbaptiste** [comment]
Hi,

Thanks for the PR. I think we are mixing two issues here that I would rather work separated. One is making SMTP configuration configurable by env vars and the other one is about how to do it, if via _Config.pm_ or _sysconf_.

This PR should be addressing only the first issue, which is the topic of issue  #34  that this PR addresses. 

The disabling of this configuration via _Config.pm_ could be implemented to make it more general to enable/disable _Config.pm_ configuration entirely instead of just the SMTP settings.  Also I think we could achieve the same thing by making all the SMTP_ vars optional, as you made the new username and password ones. If you don't set them then _Config.pm_ will not be modified with those parameters.

So, about the changes about making _SendmailModule_ configurable, I think they are ok, so if you agree, please remove from this PR the CONFIGURE_MAIL_VIA_SYSCONF check and we are good to go. You can open another issue if you want to discuss it.

**Comment by hos-ftv** [comment]
I totally agree that enabling/disabling configuration via Config.pm could be handled in a separate PR. I'll extract that and keep the idea of a global switch in mind.

Making all the `SMTP_` - vars optional was my first intention but this could/will break existing setups with [juanluisbaptiste/docker-postfix](https://github.com/juanluisbaptiste/docker-postfix) which rely on `SendmailModule`, `SendmailModule::Host` and `SendmailModule::Port` are being set to their current default values.
So I discarded this idea. If you're ok with this change I'd like to harmonize this block as you've mentioned.

Moreover, I'm not quite sure if configuring `SendmailModule` the way it is implemented in this (short) way is a good idea or if it would be better to pass in the whole module-name/-string. So instead of just only `SMTP` `Kernel::System::Email::SMTP` could be required.

**Comment by juanluisbaptiste** [comment]
> Making all the SMTP_ - vars optional was my first intention but this could/will break existing setups using juanluisbaptiste/docker-postfix (or any similar) which rely on SendmailModule, SendmailModule::Host and SendmailModule::Port are being set to their current default values.

Sorry for the delay in answering. Yes you make a point about breaking current configurations, I'll think a little bit more if there's a better way to handle this, or maybe adding a notice at bot that this changed or is going to, could be how to handle it.

**Comment by hos-ftv** [comment]
Hi @juanluisbaptiste after thinking that over it does not seem to break current configurations as non of the methods in _functions.sh_ will remove any entry from the _Config.pm_.
So existing setups have to be "cleaned up" manually before the new configuration takes effect.

**Comment by juanluisbaptiste** [comment]
Hi @hos-ftv, sorry for the late reply. I think too that as you say, while we don't remove current smtp configuration options and we handle default values we will not break current installs. Please do a clean commit with this changes, as this PR has multiple outdated commits .

Thanks.

**Comment by hos-ftv** [comment]
so I'll close this one

**Pull request closed without merging**
