### PR TITLE
fix overrides in my.cnf

### PR DESCRIPTION
**Pull request by rdxmb**
closes https://github.com/juanluisbaptiste/docker-otrs/issues/76

### CODE REVIEW

**Comment by rdxmb** [comment]
ping

**Comment by juanluisbaptiste** [comment]
Hi @rdxmb ,

Sorry for the late reply, I have had some busy days. Thanks for the PR, please rename the conf file to otrs.cnf and we're good to go.

**Comment by rdxmb** [comment]
done

**Comment by juanluisbaptiste** [comment]
Merged, thanks.

**Pull request merged**
