### PR TITLE
Added a service file for convenience

### PR DESCRIPTION
**Pull request by grantcurell**
Since this is a core service for most who are using it, it's likely they will want to run it as a service so that it comes up on boot. I've added a service file people can copy in for convenience.

### CODE REVIEW

**Comment by grantcurell** [comment]
Not sure if you want me to change it, but I didn't know what the workflow was and didn't want to pull request directly against master so I did it against otrs-6_0_x, but I first rebased it on master so the commit count is a bit wild.

**Comment by juanluisbaptiste** [comment]
Hi,

Thanks for the PR, I'm not currently using otrs-6_0_x branch, please rebase it against master.

**Comment by grantcurell** [comment]
> Hi,
> 
> Thanks for the PR, I'm not currently using otrs-6_0_x branch, please rebase it against master.

Done

**Comment by juanluisbaptiste** [comment]
Merged, thanks.

**Pull request merged**
